### ISSUE TITLE
Client crash when right clicking while exploring world

### ISSUE THREAD

**Issue by RagingSkittles** [Trikzon/shuffle#1]
Minecraft version: 1.15.2
Forge version: 31.1.0
Description: Unexpected error
java.lang.IllegalArgumentException: bound must be positive

> 	at java.util.Random.nextInt(Random.java:388) ~[?:1.8.0_51] {}
> 	at io.github.trikzon.shuffle.forge.Shuffle.onBlockRightClicked(Shuffle.java:122) ~[?:1.15.2-1.1.0] {re:classloading}
> 	at io.github.trikzon.shuffle.forge.Shuffle$$Lambda$2412/1100021468.accept(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.eventbus.EventBus.doCastFilter(EventBus.java:212) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus.lambda$addListener$11(EventBus.java:204) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
> 	at net.minecraftforge.eventbus.EventBus$$Lambda$2107/1012476940.invoke(Unknown Source) ~[?:?] {}
> 	at net.minecraftforge.eventbus.EventBus.post(EventBus.java:258) ~[eventbus-2.0.0-milestone.1-service.jar:?] {}
> 	at net.minecraftforge.common.ForgeHooks.onRightClickBlock(ForgeHooks.java:784) ~[?:?] {re:classloading}
> 	at net.minecraft.client.multiplayer.PlayerController.func_217292_a(PlayerController.java:268) ~[?:?] {re:classloading,pl:accesstransformer:B,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_147121_ag(Minecraft.java:1282) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customwindowtitle:CustomWindowTitle,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_184117_aA(Minecraft.java:1543) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customwindowtitle:CustomWindowTitle,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1376) ~[?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customwindowtitle:CustomWindowTitle,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:905) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customwindowtitle:CustomWindowTitle,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:554) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,xf:fml:customwindowtitle:CustomWindowTitle,pl:mixin:APP:assets/immersive_portals/immersive_portals.mixins_client.json:MixinMinecraftClient,pl:mixin:A,pl:runtimedistcleaner:A}
> 	at net.minecraft.client.main.Main.main(SourceFile:204) [?:?] {re:classloading}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
> 	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
> 	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
> 	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:56) [forge-1.15.2-31.1.0.jar:31.1] {}
> 	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$469/634991000.call(Unknown Source) [forge-1.15.2-31.1.0.jar:31.1] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-5.0.0-milestone.4.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-5.0.0-milestone.4.jar:?] {}
> 	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-5.0.0-milestone.4.jar:?] {}
> 	at cpw.mods.modlauncher.Launcher.run(Launcher.java:81) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}
> 	at cpw.mods.modlauncher.Launcher.main(Launcher.java:65) [modlauncher-5.0.0-milestone.4.jar:?] {re:classloading}

Timing is not consistent but can be recreated by travelling in a world while generating new chunks for 5+ minutes, then attempting to right click on any entity/block with an empty hand. Examples are opening a chest in a dungeon, right clicking on stone brick of a structure, etc.. The bug does not occur if no new chunks have been generated.

This mod is being used alongside Biomes O Plenty, The Lost Cities and Immersive Portals, all updated to latest version.

**Comment by Trikzon** [comment]
Thanks for reporting!

I'm not completely sure why it gives the error "java.lang.IllegalArgumentException: bound must be positive"
because the number I give it is always positive...
but I did find out that on the forge version of the mod just right clicking with an empty hand crashes the game.
I've now fixed that issue which i hope fixes the one you're having.
28926be
https://www.curseforge.com/minecraft/mc-mods/shuffle/files/2883014

Please try it out and if it didn't fix your issue reopen the issue :)
