### ISSUE TITLE
Option to not play sound

### ISSUE THREAD

**Issue by nco2k** [Trikzon/shuffle#13]
can you please give us an option to not play a sound when turning the shuffle mode on and off?

**Comment by Trikzon** [comment]
Added a setting in v20.6.0 for MC 1.20.6. Thanks for the suggestion.

By the way, for previous versions, the sound effect is tied to your "Players" music & sound option in game

**Comment by nco2k** [comment]
awesome! thanks for adding this. any chance you could backport to 1.20.4?
