### ISSUE TITLE
1.21 Support

### ISSUE THREAD

**Issue by GamerGuy95953** [Trikzon/shuffle#14]
Are there any plans to update the mod to 1.21? I really love this mod!

**Comment by Trikzon** [comment]
It should be updated by the end of the week.

I'll begin updating it tomorrow, so if nothing goes wrong it should be up tomorrow.

Thanks for enjoying the mod :D :heart:

**Comment by GamerGuy95953** [comment]
> It should be updated by the end of the week.
> 
> I'll begin updating it tomorrow, so if nothing goes wrong it should be up tomorrow.
> 
> Thanks for enjoying the mod :D ❤️

Great thanks! Really helps with adding depth to my builds!

**Comment by Trikzon** [comment]
Now available for 1.21 (https://modrinth.com/mod/shuffle/versions).

A version was put out yesterday, but a bug with the options screen was fixed with a newer version just now
