### ISSUE TITLE
[Request] Respect item ratios

### ISSUE THREAD

**Issue by chimericdream** [Trikzon/shuffle#8]
As far as I can tell, the mod currently just picks a random slot which has a placeable block in it. However, I'd like to be able to control the relative weight of each block type. For example, if I have 64 dirt, 32 coarse dirt, and 16 gravel, I should have a 4/7 chance of placing dirt, 2/7 coarse dirt, and 1/7 gravel.

Great mod, thanks!

**Comment by Trikzon** [comment]
That's an neat idea that has somehow never occurred to me. I will think about how I would implement it and whether I want that to be default behavior or not. I could always add it as a config option that can be toggled in an in-game UI.

For now you can get weighting by filling multiple slots with the same block. So, for example, you could fill 4 hotbar slots with dirt, 2 slots with coarse dirt, and 1 with gravel. That should give you the weights you gave in your example. However, that only allows you to weight out of 9 currently so your idea would be better.

Also, keep in mind that any feature updates will only be for the latest MC version (1.20).

Also, thank you for liking the mod :D
